### ISSUE TITLE
As an Admin/Customer/Guest, I want to be able to paginate through products with a “Load More" button so that I can easily view more products.

### ISSUE THREAD

**Issue by Nant1ng** [KYH-Net23/ProductsRepo#162]
# Acceptance Criteria

- [x] There must be a “Load More” button on the products list.
- [x] When the “Load More” button is clicked, the next set (10) of products should be loaded and appended to the currently displayed list.
- [x] Only a limited number of products (20) should be loaded initially.
- [x] The number of products being shown should be displayed along with the total number of products (e.g., "20 of 50 products showing").
- [x] If there are no more products to load, the "Load More" button should disappear.

---

# Tasks

- [x] KYH-Net23/ProductsRepo#171
    - [x] Set up backend pagination to limit the number of products returned per request (e.g., 20 per page).
    - [x] Add an endpoint to fetch additional pages of products.

- [x] KYH-Net23/Rika#213
    - [x] Create a "Load More" button at the bottom of the product list.
    - [x] Ensure the button is only visible when more products are available.

- [x] KYH-Net23/ProductsRepo#173
    - [x] On "Load More" button click, fetch the next set of products (10).
    - [x] Append new products to the existing list without a full page reload.
    - [x] Display the current number of products shown and the total number of available products.

- [x] KYH-Net23/Rika#214
    - [x] Hide the "Load More" button once all products are loaded.

- [x] #175
    - [x] Write unit tests for the pagination logic.
    - [x] Write integration tests to ensure pagination works as expected.

---

# Test Case Descriptions

- [x] Test Case 1: Successfully Fetch More Products

    **Prerequisites:**
    - There should be at least 30 products available in the database.

    **Steps:**
    - Verify that initially, 20 products are displayed on the page.
    - Click on the "Load More" button to load 10 additional products.

    **Expected Result:**
    - A total of 30 products should now be displayed on the page, reflecting the additional 10 products loaded.

---
