### ISSUE TITLE
As an Admin/Customer/Guest, I want to be able to view product details page.

### ISSUE THREAD

**Issue by zikky17** [KYH-Net23/ProductsRepo#2]
# Acceptance Criteria

- [x] The product card must be clickable so it takes the admin to the detail page.
- [x] The product details page must display product information.
- [x] Only the admin should be able to see and select the Edit button.
- [x] There must be an option to return to the products page (“go back”).

---

# Tasks

- [x] KYH-Net23/ProductsRepo#69
    - [x] Create a product model that represents the input fields that are required. (Product Name, Description, Price, Image, etc).

- [x] KYH-Net23/ProductsRepo#71
    - [x] Create a ProductService class with an interface (IProductService ).
    - [x] Create a ProductRepository class with an interface (IProductRepository ).
    - [x] Create a ProductFactory class.
    - [x] Create ProductContext that implements DbContext.

- [x] KYH-Net23/ProductsRepo#76
    - [x] GetProduct(Id) that fetch from the database

- [x] KYH-Net23/Rika#48
    - [x] Show product details
    - [x] Have a “go back” option.
    - [x] Edit button that only Admin can see

- [x] KYH-Net23/ProductsRepo#82
    - [x] Write unit tests to ensure functionality is working correctly, write integration tests to ensure it cooperates with other systems.

---

# Test Case Descriptions

- [x] Test Case 1: Successfully View Product Details

    Prerequisites:
-     Person is logged in as Admin.
-     Go to the Products page.

    Steps:
-     Admin clicks on a product card.
-     Admin gets redirected to the product details page.
    
    Expected Result:
-     Admin is redirected to the product details page, where product information is displayed.

- [x] #177

    Prerequisites:
-     Person is logged in as Admin.
-     Go to the Products page.
    
    Steps:
-     Admin clicks on a product card for a product that doesn’t exist or encounters a database error.
    
    Expected Result:
-     An error message is displayed.
-     Admin has an option to return to the products page.

---
